version: '3.3'

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.adbyte.cn:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "8080:8080"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab

volumes:
  gitlab-config:
  gitlab-data:
  gitlab-logs: