version: '3.3'

services:

  openwrt:
    container_name: openwrt
    image: registry.cn-shanghai.aliyuncs.com/suling/openwrt:latest
    command: /sbin/init
    restart: always
#    volumes:
#      - redis-data:/data
#    ports:
#      - "6379:6379"
    networks:
      - macnet

networks:
  macnet:
