version: '3.3'

services:

  postgres:
    image: postgres:11.1
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

volumes:
  postgres-data: